name: alphatrans
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openai=1.53.0
  - pyyaml=6.0.2
  - tqdm=4.66.1
  - python-dotenv=1.0.0
  - black=24.4.2
  - transformers=4.34.1
  - tree_sitter=0.20.3
  - beautifulsoup4=4.12.3
  - pytest-cov=5.0.0
  - tiktoken=0.7.0
  - sqlalchemy=2.0.37
