models:
  gpt-4o-2024-11-20:
    model_id: gpt-4o-2024-11-20
    base_url:
    api_key: "PASTE YOUR API KEY HERE"
    default_headers: {}
    total: 128000
    max_new_tokens: 16384
  deepseek-coder-33b-instruct:
    model_id: deepseek-ai/deepseek-coder-33b-instruct
    base_url: "PASTE YOUR MODEL ENDPOINT HERE"
    api_key: "PASTE YOUR API KEY HERE, IF REQUIRED"
    default_headers: {}
    total: 16384
    max_new_tokens: 4096
